コンパイルが通った
コンパイルが通ったが以下のエラー
Exception in thread "main" java.lang.NoClassDefFoundError: Node
	at Blockchain.run(Blockchain.java:46)
	at Main.main(Main.java:6)
Caused by: java.lang.ClassNotFoundException: Node
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more